#!/usr/bin/env python3
"""Generate data/races.json from structured event definitions.

Run from repo root:  python3 scripts/generate_races.py > data/races.json
"""

import json

# ---------------------------------------------------------------------------
# Coordinate lookup — all town-level, precision="town"
# ---------------------------------------------------------------------------
COORDS = {
    "Silverton, Colorado":        (37.8115, -107.6644),
    "Leadville, Colorado":        (39.2508, -106.2925),
    "Lake City, Colorado":        (38.0305, -107.3170),
    "Ouray, Colorado":            (38.1460, -107.7415),
    "Durango, Colorado":          (37.2769, -107.8766),
    "Telluride, Colorado":        (37.9375, -107.8123),
    "Creede, Colorado":           (37.8483, -106.9255),
    "Colorado Springs, Colorado": (38.8340, -104.8253),
    "Woodland Park, Colorado":    (38.9938, -105.0570),
    "Divide, Colorado":           (38.9419, -105.1572),
    "Palmer Lake, Colorado":      (39.1222, -104.9172),
    "Larkspur, Colorado":         (39.2288, -104.8845),
    "Lakewood, Colorado":         (39.7086, -105.0847),
    "Highlands Ranch, Colorado":  (39.5386, -104.9726),
    "Brighton, Colorado":         (39.9837, -104.8111),
    "Castle Rock, Colorado":      (39.3723, -104.8587),
    "Pine, Colorado":             (39.4446, -105.4812),
    "Fort Collins, Colorado":     (40.5872, -105.0770),
    "Gould, Colorado":            (40.5274, -106.0258),
    "Red Feather Lakes, Colorado":(40.8077, -105.5756),
    "Eaton, Colorado":            (40.5260, -104.7113),
    "Greeley, Colorado":          (40.4233, -104.7091),
    "Estes Park, Colorado":       (40.3772, -105.5232),
    "Steamboat Springs, Colorado":(40.4848, -106.8317),
    "Crested Butte, Colorado":    (38.8698, -106.9840),
    "Gunnison, Colorado":         (38.6477, -107.0603),
    "Grand Mesa, Colorado":       (39.1131, -108.0128),
    "Fruita, Colorado":           (39.1589, -108.7336),
    "Aspen, Colorado":            (39.1911, -106.8236),
    "Empire, Colorado":           (39.7611, -105.6830),
    "Granby, Colorado":           (40.0861, -105.9395),
    "Buena Vista, Colorado":      (38.8422, -106.1311),
    "Como, Colorado":             (39.3165, -105.8928),
    "Fairplay, Colorado":         (39.2252, -106.0020),
    "Westcliffe, Colorado":       (38.1347, -105.4658),
    "La Veta, Colorado":          (37.5050, -105.0078),
    "Canon City, Colorado":       (38.4423, -105.2349),
    "Beulah, Colorado":           (38.0750, -104.9867),
    "Longmont, Colorado":         (40.1672, -105.1019),
    "Golden, Colorado":           (39.7546, -105.2206),
    "Conifer, Colorado":          (39.5233, -105.3055),
    "Nederland, Colorado":        (39.9614, -105.5108),
}

MARQUEE = {
    "hardrock-100",
    "leadville-trail-100",
    "great-divide-ultra",
    "san-juan-solstice-50",
    "transrockies-pass-to-pub",
    "never-summer-100k",
    "high-lonesome-100",
    "telluride-mountain-run",
    "sneffles-round",
    "run-rabbit-run",
    "sangre-de-cristo-trail-festival",
    "bear-chase",
    "quad-rock",
    "ouray-100",
}

def coord(key):
    lat, lng = COORDS[key]
    return {"lat": lat, "lng": lng, "precision": "town", "derived_from": key}

def dist(label, miles=None, hours=None, loop_miles=None, stages=None, approx=False):
    d = {"label": label}
    if miles is not None:
        d["miles"] = miles
    if approx:
        d["miles_approximate"] = True
    if hours is not None:
        d["hours"] = hours
    if loop_miles is not None:
        d["loop_miles"] = loop_miles
    if stages is not None:
        d["stages"] = stages
    return d

def event(slug, name, organizer, organizer_confirmed, source,
          coord_key, town, county, region,
          ultra_distances, companion_distances,
          longest_ultra_miles, distance_category, fmt,
          date_start, date_end, date_confirmed, date_display,
          date_approx_month, date_approx_year,
          year_started, year_started_confirmed,
          status, notes):
    return {
        "slug": slug,
        "name": name,
        "organizer": organizer,
        "organizer_confirmed": organizer_confirmed,
        "source": source if isinstance(source, list) else [source],
        "coordinates": coord(coord_key),
        "location": {"town": town, "county": county if isinstance(county, list) else [county], "region": region},
        "ultra_distances": ultra_distances,
        "companion_distances": companion_distances,
        "longest_ultra_miles": longest_ultra_miles,
        "distance_category": distance_category,
        "format": fmt,
        "date_start": date_start,
        "date_end": date_end,
        "date_confirmed": date_confirmed,
        "date_display": date_display,
        "date_approx_month": date_approx_month,
        "date_approx_year": date_approx_year,
        "year_started": year_started,
        "year_started_confirmed": year_started_confirmed,
        "status": status,
        "marquee": slug in MARQUEE,
        "notes": notes,
    }

# ---------------------------------------------------------------------------
# All 75 events
# (Excluded: Ouray Mountain Trail Run, Kendall Mountain Run, Louisville Trail
#  Races, Audi Power of Four Trail Run, Colorado Trail Race)
# ---------------------------------------------------------------------------
EVENTS = [

    # ── San Juans / High Country ────────────────────────────────────────────

    event(
        slug="hardrock-100",
        name="Hardrock Hundred Mile Endurance Run",
        organizer="Hardrock Hundred Mile Endurance Run (nonprofit), directed by Dale Garland",
        organizer_confirmed=True,
        source=["hardrock100.com"],
        coord_key="Silverton, Colorado",
        town="Silverton", county=["San Juan"], region="san-juans",
        ultra_distances=[dist("102.5 mi", miles=102.5)],
        companion_distances=[],
        longest_ultra_miles=102.5, distance_category="100m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="Early July (typical; exact date shifts — course direction alternates yearly)",
        date_approx_month=7, date_approx_year=2026,
        year_started=1992, year_started_confirmed=True,
        status="active",
        notes="San Juan Mountains loop; ~33,000 ft climb; avg elevation 11,186 ft; summits Handies Peak (14,048 ft — highest point in any race in this dataset). One of the hardest ultras in the world to enter: lottery + trail-work requirement. Part of the Grand Slam of Ultrarunning.",
    ),

    event(
        slug="leadville-trail-100",
        name="Leadville Trail 100 Run",
        organizer="Life Time / Leadville Race Series",
        organizer_confirmed=True,
        source=["leadvilleraceseries.com"],
        coord_key="Leadville, Colorado",
        town="Leadville", county=["Lake"], region="san-juans",
        ultra_distances=[dist("100 mi", miles=100)],
        companion_distances=[],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start="2026-08-15", date_end="2026-08-16", date_confirmed=False,
        date_display="Aug 15–16, 2026 (confirm exact date)",
        date_approx_month=None, date_approx_year=2026,
        year_started=1983, year_started_confirmed=True,
        status="active",
        notes="aka 'Race Across the Sky'. Out-and-back on Colorado Trail & dirt roads; climbs Hope Pass (12,532 ft); ~15,744 ft total climb. Western States/Grand Slam qualifier; 30-hr cutoff.",
    ),

    event(
        slug="leadville-silver-rush-50",
        name="Leadville Silver Rush 50",
        organizer="Life Time / Leadville Race Series",
        organizer_confirmed=True,
        source=["leadvilleraceseries.com"],
        coord_key="Leadville, Colorado",
        town="Leadville", county=["Lake"], region="san-juans",
        ultra_distances=[dist("50 mi", miles=50)],
        companion_distances=["Marathon"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="Typically early–mid July (returning — see status)",
        date_approx_month=7, date_approx_year=2027,
        year_started=1994, year_started_confirmed=True,
        status="returning",
        notes="High-altitude mining-road course above 10,000 ft. 2026 run cancelled due to Willow Fire (per The Colorado Sun, July 9, 2026). Expected to return; this entry represents a typical year.",
    ),

    event(
        slug="san-juan-solstice-50",
        name="San Juan Solstice 50",
        organizer="Lake City Community (grassroots nonprofit)",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Lake City, Colorado",
        town="Lake City", county=["Hinsdale"], region="san-juans",
        ultra_distances=[dist("50 mi", miles=50)],
        companion_distances=[],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-06-20", date_end=None, date_confirmed=True,
        date_display="June 20, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=1995, year_started_confirmed=True,
        status="active",
        notes="San Juan Mountains; ~12,000 ft climb along the Continental Divide. Lottery entry (300 runners); Western States qualifier; benefits Lake City EMS.",
    ),

    event(
        slug="ouray-100",
        name="Ouray 100 Mile Endurance Run",
        organizer="Ouray Ultras LLC",
        organizer_confirmed=True,
        source=["ouray100.com"],
        coord_key="Ouray, Colorado",
        town="Ouray", county=["Ouray"], region="san-juans",
        ultra_distances=[dist("100 mi", miles=100)],
        companion_distances=[],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="Typically mid-July (returning — see status)",
        date_approx_month=7, date_approx_year=2027,
        year_started=2014, year_started_confirmed=True,
        status="returning",
        notes="San Juan Mountains; ~41,862 ft gain; historic mining routes. 2026 edition cancelled ~2 weeks before race day due to Gold Mountain wildfire. Expected to return; this entry represents a typical year.",
    ),

    event(
        slug="ouray-50",
        name="Ouray 50 Mile Endurance Run",
        organizer="Ouray Ultras LLC",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Ouray, Colorado",
        town="Ouray", county=["Ouray"], region="san-juans",
        ultra_distances=[dist("50 mi", miles=50)],
        companion_distances=[],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="September 2026 (dates vary ~Sept 12–14 across sources)",
        date_approx_month=9, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="San Juan Mountains. Sister event to the Ouray 100; no longer a UTMB qualifier (stopped 2022).",
    ),

    event(
        slug="sneffles-round",
        name='The Sneffles Round ("Sneffelupagus")',
        organizer="Sky Pilots (club)",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Ouray, Colorado",
        town="Ouray", county=["Ouray"], region="san-juans",
        ultra_distances=[dist("~75 mi", miles=75, approx=True)],
        companion_distances=[],
        longest_ultra_miles=75, distance_category="100k", fmt="standard",
        date_start="2026-09-05", date_end=None, date_confirmed=True,
        date_display="Sept 5, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="~43,000 ft climb; ~34 peaks including 14er Mt. Sneffels; ~70% off-trail; self-navigated. Free entry; applicants vetted for mountaineering/routefinding skill; ~35-runner cap; 100-hr limit.",
    ),

    event(
        slug="san-juan-softie-100",
        name="San Juan Softie 100",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultrasignup.com"],
        coord_key="Durango, Colorado",
        town="Durango", county=["La Plata"], region="san-juans",
        ultra_distances=[dist("100 mi", miles=100)],
        companion_distances=[],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="~Aug 14, 2026 (approximate)",
        date_approx_month=8, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="San Juan Mountains region; less technical variant of the area's high-mountain 100-milers. Featured on the curated UltraSignup Colorado list.",
    ),

    event(
        slug="telluride-mountain-run",
        name="Telluride Mountain Run",
        organizer="Highline Running Adventures (Jared Vilhauer)",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Telluride, Colorado",
        town="Telluride", county=["San Miguel"], region="san-juans",
        ultra_distances=[dist("100K", miles=62.1), dist("40 mi", miles=40)],
        companion_distances=["Hill Climb & shorter options historically offered"],
        longest_ultra_miles=62.1, distance_category="100k", fmt="standard",
        date_start="2026-08-22", date_end="2026-08-23", date_confirmed=True,
        date_display="Aug 22–23, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2013, year_started_confirmed=True,
        status="active",
        notes="High San Juans above Telluride; above 13,000 ft; Mile-and-a-Half-of-Sky ridge; Telluride Peak (13,509 ft). Founded by Dakota Jones as a 38-miler. Exact 2026 distance lineup should be confirmed with organizer.",
    ),

    event(
        slug="box-canyon-trail-races",
        name="Box Canyon Trail Races",
        organizer="Confluence Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Telluride, Colorado",
        town="Telluride", county=["San Miguel"], region="san-juans",
        ultra_distances=[dist("30K", miles=18.6)],
        companion_distances=["10 mi"],
        longest_ultra_miles=18.6, distance_category="sub-50k", fmt="standard",
        date_start="2026-07-25", date_end=None, date_confirmed=True,
        date_display="July 25, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Climbs from town past Bridal Veil Falls to ~13,000 ft. Ultra-adjacent event (30K is below the standard 50K threshold); grouped with Telluride-area ultra race weekends.",
    ),

    event(
        slug="creede-50-100",
        name="Creede 50/100",
        organizer="Tempest Adventures LLC",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Creede, Colorado",
        town="Creede", county=["Mineral"], region="san-juans",
        ultra_distances=[dist("100 mi", miles=100), dist("50 mi", miles=50)],
        companion_distances=[],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start="2026-07-25", date_end=None, date_confirmed=True,
        date_display="July 25, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="San Juans; climbs above 12,000 ft; 20,000+ ft gain; Continental Divide singletrack; start/finish Basham Park. 100-runner cap; USFS permitted; self-reliant ethos. Not the same event as Creede Mountain Run (different organizer, different history).",
    ),

    event(
        slug="creede-mountain-run",
        name="Creede Mountain Run",
        organizer="Creede & Mineral County Chamber of Commerce",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Creede, Colorado",
        town="Creede", county=["Mineral"], region="san-juans",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["22 mi", "12 mi", "2 mi fun run"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-09-05", date_end=None, date_confirmed=True,
        date_display="Sept 5, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=1987, year_started_confirmed=True,
        status="active",
        notes="Community race; distinct from the Tempest Adventures Creede 50/100 (different organizer, different history).",
    ),

    event(
        slug="silverton-alpine-50k",
        name="Silverton Alpine Marathon & 50K",
        organizer="Aravaipa Running",
        organizer_confirmed=True,
        source=["aravaiparunning.com"],
        coord_key="Silverton, Colorado",
        town="Silverton", county=["San Juan"], region="san-juans",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["Marathon", "8 mi"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-07-18", date_end=None, date_confirmed=True,
        date_display="July 18, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Alpine Loop; high point 12,930 ft at California Pass.",
    ),

    # ── Front Range / Colorado Springs ────────────────────────────────────

    event(
        slug="pikes-peak-ultra",
        name="Pikes Peak Ultra",
        organizer="Mad Moose Events (founded by Justin Ricks)",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("50 mi", miles=50), dist("50K", miles=31.1)],
        companion_distances=["30K", "20K"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-07-25", date_end=None, date_confirmed=True,
        date_display="July 25, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2015, year_started_confirmed=True,
        status="active",
        notes="Foothills/mountain terrain beneath Pikes Peak; longer courses summit Mt. Rosa. Considered a more approachable Front Range ultra.",
    ),

    event(
        slug="valkyrie-trail-race",
        name="Valkyrie Trail Race",
        organizer="Mad Moose Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["Marathon", "30K", "Half", "8 mi", "4 mi"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-05-09", date_end=None, date_confirmed=True,
        date_display="May 9, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Cheyenne Mountain State Park. Women-centered trail event.",
    ),

    event(
        slug="ram-party-trail-runs",
        name="Ram Party Trail Runs",
        organizer="Aravaipa Running",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("55 mi", miles=55), dist("50K", miles=31.1)],
        companion_distances=["60K", "24K", "15K"],
        longest_ultra_miles=55, distance_category="50m", fmt="standard",
        date_start="2026-05-16", date_end=None, date_confirmed=True,
        date_display="May 16, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Rampart Reservoir / Buffalo Lodge Bicycle Resort; high point 9,500 ft. Weekend festival format.",
    ),

    event(
        slug="falcon-50",
        name="Falcon 50",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("50 mi", miles=50), dist("50K", miles=31.1)],
        companion_distances=[],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-04-25", date_end=None, date_confirmed=True,
        date_display="April 25, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Front Range foothills. Featured on the UltraSignup Colorado list.",
    ),

    event(
        slug="cheyenne-mountain-trail-races",
        name="Cheyenne Mountain Trail Races",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["25K", "10K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-04-25", date_end=None, date_confirmed=True,
        date_display="April 25, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Cheyenne Mountain State Park. Distances confirmed: 50K / 25K / 10K.",
    ),

    event(
        slug="take-5-in-the-garden",
        name="Take 5 in the Garden",
        organizer="Mad Moose Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("Timed (duration TBD — verify with organizer)", hours=None)],
        companion_distances=["Road + trail short options"],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2026-05-02", date_end=None, date_confirmed=True,
        date_display="May 2, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Garden of the Gods area. Timed ultra-format event; specific duration not listed in source — confirm with organizer.",
    ),

    event(
        slug="ring-the-springs",
        name="Ring the Springs",
        organizer="Mad Moose Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("100K", miles=62.1), dist("50K", miles=31.1)],
        companion_distances=["35K"],
        longest_ultra_miles=62.1, distance_category="100k", fmt="standard",
        date_start="2026-06-20", date_end=None, date_confirmed=True,
        date_display="June 20, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Ring the Peak trail system.",
    ),

    event(
        slug="bobcat-trail-race",
        name="Bobcat Trail Race",
        organizer="Mad Moose Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["25K", "10K", "5K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-10-17", date_end=None, date_confirmed=True,
        date_display="Oct 17, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Palmer Park sandstone/mesa terrain.",
    ),

    event(
        slug="rattler-trail-race",
        name="Rattler Trail Race",
        organizer="Mad Moose Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["25K", "10K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2027-04-17", date_end=None, date_confirmed=True,
        date_display="April 17, 2027",
        date_approx_month=None, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Palmer Park.",
    ),

    event(
        slug="colorado-cold-rush-ultra",
        name="Colorado Cold Rush Ultra",
        organizer="Revenant Running",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["Half", "10K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-11-21", date_end=None, date_confirmed=True,
        date_display="Nov 21, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Bear Creek Regional Park, High Drive, Gold Camp Road; ~9,000 ft. Winter conditions likely (snow/ice).",
    ),

    event(
        slug="stories-ultra",
        name="Stories Ultra",
        organizer="Human Potential Running Series",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Colorado Springs, Colorado",
        town="Colorado Springs", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("30-hr", hours=30), dist("15-hr", hours=15), dist("6-hr", hours=6)],
        companion_distances=["Half", "10K"],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2027-02-06", date_end="2027-02-07", date_confirmed=True,
        date_display="Feb 6–7, 2027",
        date_approx_month=None, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="No podium/age-group awards, per HPRS format.",
    ),

    event(
        slug="above-the-clouds-ultra",
        name="Above the Clouds Ultra",
        organizer="Revenant Running",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Woodland Park, Colorado",
        town="Woodland Park", county=["Teller"], region="front-range-cs",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["10K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-10-03", date_end=None, date_confirmed=True,
        date_display="Oct 3, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Starts/finishes at Woodland Park Middle School. ~4,137 ft gain on the 50K; ascends Lovell Gulch to Rampart Range Road, circles Rampart Reservoir; Pikes Peak views.",
    ),

    event(
        slug="great-divide-ultra",
        name="The Great Divide Ultra",
        organizer="Revenant Running",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Divide, Colorado",
        town="Divide", county=["Teller"], region="front-range-cs",
        ultra_distances=[dist("100 mi", miles=100), dist("100K", miles=62.1), dist("50K", miles=31.1)],
        companion_distances=["25K"],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start="2026-06-06", date_end="2026-06-07", date_confirmed=True,
        date_display="June 6–7, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Mueller State Park; rolling single/doubletrack; 9,000+ ft elevation. First 100-miler on the CO calendar each year; non-technical; features a night 'Dark Divide' run. Three start-time variants per distance.",
    ),

    event(
        slug="24-hours-of-palmer-lake",
        name="24 Hours of Palmer Lake",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultrasignup.com"],
        coord_key="Palmer Lake, Colorado",
        town="Palmer Lake", county=["El Paso"], region="front-range-cs",
        ultra_distances=[dist("24-hr", hours=24)],
        companion_distances=[],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2026-09-26", date_end=None, date_confirmed=True,
        date_display="Sept 26, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="0.82-mi loop at 7,240 ft.",
    ),

    event(
        slug="greenland-trail-races",
        name="Greenland Trail Races",
        organizer="Colorado Runner Events",
        organizer_confirmed=True,
        source=["runguides.com"],
        coord_key="Larkspur, Colorado",
        town="Larkspur", county=["Douglas"], region="front-range-cs",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["25K", "8 mi", "4 mi"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-05-02", date_end=None, date_confirmed=True,
        date_display="May 2, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Greenland Open Space (near Larkspur). 2026 RRCA National 50K Championship; billed as 'Colorado's fastest 50K'.",
    ),

    # ── Denver Metro / N. Front Range ──────────────────────────────────────

    event(
        slug="bear-chase",
        name="The Bear Chase",
        organizer="Aravaipa Running",
        organizer_confirmed=True,
        source=["aravaiparunning.com"],
        coord_key="Lakewood, Colorado",
        town="Lakewood", county=["Jefferson"], region="denver-metro",
        ultra_distances=[dist("100K", miles=62.1), dist("50 mi", miles=50), dist("50K", miles=31.1)],
        companion_distances=["Half", "10K", "5K"],
        longest_ultra_miles=62.1, distance_category="100k", fmt="standard",
        date_start="2026-10-03", date_end="2026-10-04", date_confirmed=True,
        date_display="Oct 3–4, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2010, year_started_confirmed=True,
        status="active",
        notes="Bear Creek Lake Park, Lakewood. 100K added 2013; beginner-friendly; benefits Lakewood open space.",
    ),

    event(
        slug="chase-the-moon",
        name="Chase the Moon 12 Hour Endurance Run",
        organizer="Aravaipa Running (formerly HAL Sports)",
        organizer_confirmed=True,
        source=["runningintheusa.com"],
        coord_key="Highlands Ranch, Colorado",
        town="Highlands Ranch", county=["Douglas"], region="denver-metro",
        ultra_distances=[dist("12-hr", hours=12), dist("50K", miles=31.1)],
        companion_distances=["6-hr", "3-hr", "Relays"],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2026-06-27", date_end=None, date_confirmed=True,
        date_display="June 27, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Overnight 7 PM–7 AM run under the full moon. Offers a standard 50K option alongside the timed formats.",
    ),

    event(
        slug="barr-lake-trail-race",
        name="Barr Lake Trail Race",
        organizer="Aravaipa Running",
        organizer_confirmed=True,
        source=["aravaiparunning.com"],
        coord_key="Brighton, Colorado",
        town="Brighton", county=["Adams"], region="denver-metro",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["30K", "Half", "15K", "5K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-06-13", date_end=None, date_confirmed=True,
        date_display="June 13, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2020, year_started_confirmed=False,
        status="active",
        notes="Flat and fast course around Barr Lake State Park.",
    ),

    event(
        slug="rock-hawk-trail-races",
        name="Rock Hawk Trail Races",
        organizer="Aravaipa Running",
        organizer_confirmed=True,
        source=["aravaiparunning.com"],
        coord_key="Castle Rock, Colorado",
        town="Castle Rock", county=["Douglas"], region="denver-metro",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["25K", "10K", "5K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-08-29", date_end=None, date_confirmed=True,
        date_display="Aug 29, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes=None,
    ),

    event(
        slug="indian-creek-trail-runs",
        name="Indian Creek Trail Runs",
        organizer="Human Potential Running Series",
        organizer_confirmed=True,
        source=["humanpotentialrunning.com"],
        coord_key="Pine, Colorado",
        town="Pine / Sedalia", county=["Douglas", "Jefferson"], region="denver-metro",
        ultra_distances=[dist("50 mi", miles=50), dist("55K", miles=34.2)],
        companion_distances=["15 mi", "8K"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-10-17", date_end=None, date_confirmed=True,
        date_display="Oct 17, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Pike National Forest foothills south of Denver.",
    ),

    event(
        slug="north-fork-trail-race",
        name="North Fork Trail Race",
        organizer="Human Potential Running Series",
        organizer_confirmed=True,
        source=["humanpotentialrunning.com"],
        coord_key="Pine, Colorado",
        town="Pine", county=["Jefferson"], region="denver-metro",
        ultra_distances=[dist("50 mi", miles=50), dist("50K", miles=31.1)],
        companion_distances=[],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="May 2027 (TBD)",
        date_approx_month=5, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="100% soft-surface singletrack; 1996 burn-scar terrain SW of Denver (Buffalo Creek area). Proceeds support the North Fork Volunteer Fire Dept.",
    ),

    event(
        slug="sawmill-trail-runs",
        name="Sawmill Trail Runs",
        organizer="Human Potential Running Series",
        organizer_confirmed=True,
        source=["humanpotentialrunning.com"],
        coord_key="Pine, Colorado",
        town="Pine", county=["Jefferson", "Park"], region="denver-metro",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["16 mi", "8 mi"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-12-05", date_end=None, date_confirmed=True,
        date_display="Dec 5, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2013, year_started_confirmed=True,
        status="active",
        notes="Staunton State Park. Started as an informal 'Fat Ass' event in 2013; became an official race in 2017; moved to Staunton in 2021.",
    ),

    event(
        slug="golden-gate-dirty-30",
        name="Golden Gate Dirty 30",
        organizer="Formerly independent RD",
        organizer_confirmed=False,
        source=["dirty30.org"],
        coord_key="Golden, Colorado",
        town="Golden Gate Canyon", county=["Jefferson", "Gilpin"], region="denver-metro",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=[],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="N/A (permanently cancelled)",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="discontinued",
        notes="Golden Gate Canyon State Park. Official site (dirty30.org) states: 'Dirty 30 is permanently Cancelled.'",
    ),

    event(
        slug="quad-rock",
        name="Quad Rock 50/25",
        organizer="Gnar Runners",
        organizer_confirmed=True,
        source=["gnarrunners.com"],
        coord_key="Fort Collins, Colorado",
        town="Fort Collins / Bellvue", county=["Larimer"], region="denver-metro",
        ultra_distances=[dist("50 mi", miles=50)],
        companion_distances=["25 mi"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-05-09", date_end=None, date_confirmed=True,
        date_display="May 9, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Lory State Park & Horsetooth Mountain Open Space. Anchor race of the 'Gnar Slam'.",
    ),

    event(
        slug="never-summer-100k",
        name="Never Summer 100K & 60K",
        organizer="Gnar Runners",
        organizer_confirmed=True,
        source=["gnarrunners.com"],
        coord_key="Gould, Colorado",
        town="Gould", county=["Jackson"], region="denver-metro",
        ultra_distances=[dist("100K", miles=62.1), dist("60K", miles=37.3)],
        companion_distances=[],
        longest_ultra_miles=62.1, distance_category="100k", fmt="standard",
        date_start="2026-07-24", date_end="2026-07-25", date_confirmed=True,
        date_display="July 24–25, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Never Summer Mountains / Medicine Bow Mountains border; near RMNP; ~14,500 ft gain; high point North Diamond Peak (11,852 ft). Western States qualifier for 100K finishers under 23 hrs; sells out yearly.",
    ),

    event(
        slug="colorado-24-hour-run",
        name="Colorado 24 Hour Run",
        organizer="Gnar Runners",
        organizer_confirmed=True,
        source=["gnarrunners.com"],
        coord_key="Fort Collins, Colorado",
        town="Fort Collins", county=["Larimer"], region="denver-metro",
        ultra_distances=[dist("24-hr", hours=24), dist("12-hr", hours=12)],
        companion_distances=["6-hr"],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2026-10-31", date_end="2026-11-01", date_confirmed=True,
        date_display="Oct 31–Nov 1, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Flat one-mile loop.",
    ),

    event(
        slug="red-feather-trail-jamboree",
        name="Red Feather Trail Jamboree",
        organizer="Gnar Runners",
        organizer_confirmed=True,
        source=["gnarrunners.com"],
        coord_key="Red Feather Lakes, Colorado",
        town="Red Feather Lakes", county=["Larimer"], region="denver-metro",
        ultra_distances=[dist("50 mi", miles=50), dist("50K", miles=31.1)],
        companion_distances=["Half"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-09-25", date_end="2026-09-27", date_confirmed=True,
        date_display="Sept 25–27, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes=None,
    ),

    event(
        slug="weld-your-mettle",
        name="Weld Your Mettle Running Festival",
        organizer="Independent",
        organizer_confirmed=False,
        source=["runningintheusa.com"],
        coord_key="Eaton, Colorado",
        town="Eaton", county=["Weld"], region="denver-metro",
        ultra_distances=[
            dist("36-hr", hours=36), dist("24-hr", hours=24),
            dist("12-hr", hours=12), dist("9-hr", hours=9),
            dist("6-hr", hours=6), dist("3-hr", hours=3),
        ],
        companion_distances=["7K", "Relay options"],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2027-06-05", date_end="2027-06-06", date_confirmed=True,
        date_display="June 5–6, 2027",
        date_approx_month=None, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Plains terrain (not mountain). Virtual option available.",
    ),

    event(
        slug="noco-urban-ultra",
        name="NoCo Urban Ultra & Relay",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Greeley, Colorado",
        town="Greeley", county=["Weld"], region="denver-metro",
        ultra_distances=[dist("100 mi", miles=100), dist("50 mi", miles=50)],
        companion_distances=[],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start="2027-04-11", date_end=None, date_confirmed=True,
        date_display="April 11, 2027",
        date_approx_month=None, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Urban Greeley course. Solo or relay options for both distances.",
    ),

    # ── Estes Park / RMNP ─────────────────────────────────────────────────

    event(
        slug="rockys-backyard-ultra",
        name="Rocky's Backyard Ultra",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultrasignup.com"],
        coord_key="Estes Park, Colorado",
        town="Estes Park", county=["Larimer"], region="estes-park",
        ultra_distances=[dist("Backyard (4.167 mi/loop)", loop_miles=4.167)],
        companion_distances=[],
        longest_ultra_miles=None, distance_category="backyard", fmt="backyard",
        date_start="2026-10-10", date_end=None, date_confirmed=True,
        date_display="Oct 10, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Trails bordering Rocky Mountain National Park, at the YMCA of the Rockies; ~500 ft gain per loop. $1,000 cash prize + buckles for 100-mile finishers.",
    ),

    event(
        slug="estes-park-backyard-ultra",
        name="Estes Park's Backyard Ultra",
        organizer="Running Wild Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Estes Park, Colorado",
        town="Estes Park", county=["Larimer"], region="estes-park",
        ultra_distances=[dist("Backyard (4.252 mi/loop)", loop_miles=4.252)],
        companion_distances=[],
        longest_ultra_miles=None, distance_category="backyard", fmt="backyard",
        date_start="2026-06-27", date_end=None, date_confirmed=True,
        date_display="June 27, 2026 (4 PM start)",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Lake Estes paved loop.",
    ),

    event(
        slug="samsons-revenge-trail-race",
        name="Samson's Revenge Trail Race",
        organizer="Independent",
        organizer_confirmed=False,
        source=["runningintheusa.com"],
        coord_key="Estes Park, Colorado",
        town="Estes Park", county=["Larimer"], region="estes-park",
        ultra_distances=[dist("55K", miles=34.2)],
        companion_distances=["27K", "10K"],
        longest_ultra_miles=34.2, distance_category="50k", fmt="standard",
        date_start="2027-05-22", date_end=None, date_confirmed=True,
        date_display="May 22, 2027",
        date_approx_month=None, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Estes Park / RMNP-area foothills.",
    ),

    event(
        slug="estes-epic-ultra",
        name="Estes Epic Ultra Run & MTB Race",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Estes Park, Colorado",
        town="Estes Park", county=["Larimer"], region="estes-park",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["15 mi"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-09-26", date_end="2026-09-27", date_confirmed=True,
        date_display="Sept 26–27, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Combined running + MTB weekend event.",
    ),

    # ── Mountains / Western Slope ──────────────────────────────────────────

    event(
        slug="run-rabbit-run",
        name="Run Rabbit Run",
        organizer="Independent (founded/directed by Fred Abramowitz & Paul Sachs)",
        organizer_confirmed=True,
        source=["runrabbitrun.org"],
        coord_key="Steamboat Springs, Colorado",
        town="Steamboat Springs", county=["Routt"], region="mountains-western-slope",
        ultra_distances=[dist("100 mi", miles=100), dist("50 mi", miles=50)],
        companion_distances=[],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start="2026-09-18", date_end="2026-09-19", date_confirmed=True,
        date_display="Sept 18–19, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2007, year_started_confirmed=True,
        status="active",
        notes="Routt National Forest; ~22,000 ft gain (100 mi) / ~9,000 ft (50 mi). 'Hares vs. Tortoises' staggered-start format. $100,000+ overall purse, $20,000 to each 100-mile winner — largest payout of any US ultra. ~$600,000 donated to charity.",
    ),

    event(
        slug="continental-divide-trail-run",
        name="Continental Divide Trail Run",
        organizer="Steamboat Running Series",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Steamboat Springs, Colorado",
        town="Steamboat Springs", county=["Routt"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["16 mi", "8K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-08-29", date_end=None, date_confirmed=True,
        date_display="Aug 29, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Steamboat Ski Area base; Continental Divide; Mt. Werner area.",
    ),

    event(
        slug="crested-butte-ultra",
        name="Crested Butte Ultra",
        organizer="Mad Moose Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Crested Butte, Colorado",
        town="Crested Butte", county=["Gunnison"], region="mountains-western-slope",
        ultra_distances=[dist("50 mi", miles=50), dist("55K", miles=34.2)],
        companion_distances=["35K"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-09-26", date_end=None, date_confirmed=True,
        date_display="Sept 26, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Gunnison National Forest singletrack. Fall-foliage timing.",
    ),

    event(
        slug="grand-traverse-mountain-run",
        name="The Grand Traverse (Mountain Run)",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Crested Butte, Colorado",
        town="Crested Butte", county=["Gunnison"], region="mountains-western-slope",
        ultra_distances=[dist("40 mi", miles=40)],
        companion_distances=[],
        longest_ultra_miles=40, distance_category="50k", fmt="standard",
        date_start="2026-09-05", date_end=None, date_confirmed=True,
        date_display="Sept 5, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Point-to-point across the Elk Mountains. Companion event to the winter Grand Traverse ski race.",
    ),

    event(
        slug="sage-burner-trail-races",
        name="Sage Burner Trail Races",
        organizer="Mad Moose Events (formerly One Love Endurance)",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Gunnison, Colorado",
        town="Gunnison", county=["Gunnison"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["28K", "15K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-10-03", date_end=None, date_confirmed=True,
        date_display="Oct 3, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2008, year_started_confirmed=True,
        status="active",
        notes="Hartman Rocks high-desert sagebrush terrain (near Gunnison). A contrast to CO's typical alpine ultras.",
    ),

    event(
        slug="grand-mesa-ultras",
        name="Grand Mesa Ultras",
        organizer="Best Slope Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Grand Mesa, Colorado",
        town="Grand Mesa", county=["Mesa", "Delta"], region="mountains-western-slope",
        ultra_distances=[dist("50 mi", miles=50), dist("55K", miles=34.2)],
        companion_distances=["30K"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="~July 25, 2026 (approximate)",
        date_approx_month=7, date_approx_year=2026,
        year_started=2010, year_started_confirmed=True,
        status="active",
        notes="World's largest flat-topped mountain; alpine lakes; 10,000+ ft. Cash prizes for top 3 M/F; on-mountain camping.",
    ),

    event(
        slug="powderhorn-mountain-ultra",
        name="Powderhorn Mountain Ultra & Vert Challenge",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Grand Mesa, Colorado",
        town="Mesa", county=["Mesa"], region="mountains-western-slope",
        ultra_distances=[dist("12-hr", hours=12), dist("6-hr", hours=6)],
        companion_distances=["Vertical challenge (10K loop, 1,546 ft gain)"],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2026-07-18", date_end=None, date_confirmed=True,
        date_display="July 18, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Powderhorn Resort (on the Grand Mesa).",
    ),

    event(
        slug="kessel-run-ultra",
        name="Kessel Run Ultra",
        organizer="Mad Moose Events",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Fruita, Colorado",
        town="Fruita", county=["Mesa"], region="mountains-western-slope",
        ultra_distances=[dist("50 mi", miles=50), dist("40 mi", miles=40), dist("50K", miles=31.1)],
        companion_distances=["20 mi", "10 mi"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-11-07", date_end=None, date_confirmed=True,
        date_display="Nov 7, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Desert terrain near Colorado National Monument; Zippity-Do-Da singletrack. Camping available on-site.",
    ),

    event(
        slug="aspen-backcountry",
        name="Aspen Backcountry",
        organizer="Aravaipa Running",
        organizer_confirmed=True,
        source=["aravaiparunning.com"],
        coord_key="Aspen, Colorado",
        town="Aspen", county=["Pitkin"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["Marathon", "Half"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-08-01", date_end=None, date_confirmed=True,
        date_display="Aug 1, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Out-and-back to McNamara Hut; Elk Mountains backcountry singletrack above 10,000 ft. CORSAR card required.",
    ),

    event(
        slug="devil-on-the-divide",
        name="Devil on the Divide",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultrasignup.com"],
        coord_key="Empire, Colorado",
        town="Empire / Idaho Springs", county=["Clear Creek"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["22K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-09-12", date_end=None, date_confirmed=True,
        date_display="Sept 12, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Exceeds 13,000 ft; 6,500+ ft climb; 80% of course above 10,000 ft. Requires prior ultra experience for the 50K.",
    ),

    event(
        slug="snow-mountain-ranch-festival",
        name="Snow Mountain Ranch Trail Running Festival",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Granby, Colorado",
        town="Granby / Grand Lake", county=["Grand"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["33K", "Half", "10K", "5K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-09-12", date_end=None, date_confirmed=True,
        date_display="Sept 12, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Snow Mountain Ranch YMCA property.",
    ),

    event(
        slug="summits-trail-runs",
        name="Summits Trail Runs",
        organizer="Human Potential Running Series",
        organizer_confirmed=True,
        source=["humanpotentialrunning.com"],
        coord_key="Granby, Colorado",
        town="Granby", county=["Grand"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1), dist("14-hr timed", hours=14)],
        companion_distances=["Marathon", "Half Marathon", "6 mi"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-06-13", date_end=None, date_confirmed=True,
        date_display="June 13, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Granby Ranch. Confirmed distances: 50K, Marathon, Half Marathon, 6 mi, plus a 14-hr timed 'Elevation Challenge' option.",
    ),

    event(
        slug="race-the-ranch-snowshoe-ultra",
        name="Race The Ranch Snowshoe Ultra",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Granby, Colorado",
        town="Granby", county=["Grand"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["25K", "5K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-09-27", date_end=None, date_confirmed=True,
        date_display="Sept 27, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes=None,
    ),

    event(
        slug="west-line-winder",
        name="West Line Winder",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Buena Vista, Colorado",
        town="Buena Vista", county=["Chaffee"], region="mountains-western-slope",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=[],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-09-26", date_end=None, date_confirmed=True,
        date_display="Sept 26, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="~4,000 ft climb near the Collegiate Peaks.",
    ),

    event(
        slug="collegiate-peaks-trail-run",
        name="Collegiate Peaks Trail Run",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Buena Vista, Colorado",
        town="Buena Vista", county=["Chaffee"], region="mountains-western-slope",
        ultra_distances=[dist("50 mi", miles=50)],
        companion_distances=["25 mi"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="May 2027 (TBD)",
        date_approx_month=5, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Long-running local race in the Collegiate Peaks area near Buena Vista. Specific 2027 date unconfirmed.",
    ),

    event(
        slug="transrockies-pass-to-pub",
        name="TransRockies Run: Pass to Pub",
        organizer="TransRockies Run (RD Aaron McConnell)",
        organizer_confirmed=True,
        source=["transrockiesrun.com"],
        coord_key="Leadville, Colorado",
        town="Leadville to Red Cliff", county=["Lake", "Eagle"], region="mountains-western-slope",
        ultra_distances=[dist("Full Pint 51 mi (3-day stage)", miles=51, stages=3),
                         dist("Half Pint 35 mi (3-day stage)", miles=35, stages=3)],
        companion_distances=[],
        longest_ultra_miles=51, distance_category="stage", fmt="stage",
        date_start="2026-07-19", date_end="2026-07-21", date_confirmed=True,
        date_display="July 19–21, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="3-day stage race from Leadville to Red Cliff; crosses Hope Pass and the Continental Divide. Replaced the discontinued multi-day TransRockies Run format. Capped at 500 runners.",
    ),

    event(
        slug="high-lonesome-100",
        name="High Lonesome 100",
        organizer="Freestone Endurance",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Buena Vista, Colorado",
        town="Mount Princeton / Buena Vista area", county=["Chaffee"], region="mountains-western-slope",
        ultra_distances=[dist("100 mi", miles=100)],
        companion_distances=[],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="Late July 2026 (approximate)",
        date_approx_month=7, date_approx_year=2026,
        year_started=2017, year_started_confirmed=True,
        status="active",
        notes="Sawatch Range; Collegiate Peaks region; five alpine passes; 13,150 ft high point. Two-pool lottery; trail-work requirement; Western States qualifier; competitive/elite field.",
    ),

    # ── Fairplay / South Park ─────────────────────────────────────────────

    event(
        slug="silverheels-trail-runs",
        name="Silverheels Trail Runs",
        organizer="Human Potential Running Series",
        organizer_confirmed=True,
        source=["runsignup.com"],
        coord_key="Como, Colorado",
        town="Como", county=["Park"], region="fairplay-south-park",
        ultra_distances=[dist("100 mi", miles=100), dist("100K", miles=62.1),
                         dist("50 mi", miles=50), dist("60K", miles=37.3)],
        companion_distances=["19 mi", "10 mi"],
        longest_ultra_miles=100, distance_category="100m", fmt="standard",
        date_start="2026-07-10", date_end="2026-07-11", date_confirmed=True,
        date_display="July 10–11, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Avg elevation over 10,000 ft. May correspond to what some aggregators list as 'Fairplay 100M/100K' — both refer to this HPRS event in Como/Park County.",
    ),

    event(
        slug="sheep-mountain-trail-runs",
        name="Sheep Mountain Trail Runs",
        organizer="Human Potential Running Series",
        organizer_confirmed=True,
        source=["runsignup.com"],
        coord_key="Fairplay, Colorado",
        town="Fairplay", county=["Park"], region="fairplay-south-park",
        ultra_distances=[dist("50 mi", miles=50), dist("50K", miles=31.1)],
        companion_distances=["Half"],
        longest_ultra_miles=50, distance_category="50m", fmt="standard",
        date_start="2026-08-01", date_end=None, date_confirmed=True,
        date_display="Aug 1, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=2015, year_started_confirmed=True,
        status="active",
        notes="300-runner cap; 50K distance added 2018.",
    ),

    # ── Southern Colorado ─────────────────────────────────────────────────

    event(
        slug="sangre-de-cristo-trail-festival",
        name="Sangre de Cristo Trail Festival",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Westcliffe, Colorado",
        town="Westcliffe", county=["Custer"], region="southern-colorado",
        ultra_distances=[dist("200 mi", miles=200), dist("100 mi", miles=100),
                         dist("100K", miles=62.1), dist("50 mi", miles=50),
                         dist("50K", miles=31.1)],
        companion_distances=["Shorter options"],
        longest_ultra_miles=200, distance_category="200m+", fmt="standard",
        date_start="2026-09-26", date_end="2026-09-27", date_confirmed=True,
        date_display="Sept 26–27, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Rainbow Trail beneath the Sangre de Cristo peaks. Widest distance range of any CO ultra event: 50K through 200 mi.",
    ),

    event(
        slug="wild-wahatoya-runs",
        name="WILD Wahatoya Runs",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="La Veta, Colorado",
        town="La Veta", county=["Huerfano"], region="southern-colorado",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["Half", "8 mi"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start="2026-09-26", date_end=None, date_confirmed=True,
        date_display="Sept 26, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Views of the Spanish Peaks.",
    ),

    event(
        slug="bridge-burner-ultra",
        name="Bridge Burner Ultra",
        organizer="Revenant Running",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Canon City, Colorado",
        town="Canon City", county=["Fremont"], region="southern-colorado",
        ultra_distances=[dist("35 mi", miles=35), dist("50K", miles=31.1)],
        companion_distances=["35K", "10K"],
        longest_ultra_miles=35, distance_category="50k", fmt="standard",
        date_start="2026-10-24", date_end=None, date_confirmed=True,
        date_display="Oct 24, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Royal Gorge Mountain Park. The 35-mi loop crosses the Royal Gorge Bridge.",
    ),

    event(
        slug="royal-gorge-groove",
        name="Royal Gorge Groove",
        organizer="Revenant Running",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Canon City, Colorado",
        town="Canon City", county=["Fremont"], region="southern-colorado",
        ultra_distances=[dist("50K", miles=31.1)],
        companion_distances=["30K", "20K", "13K", "5K"],
        longest_ultra_miles=31.1, distance_category="50k", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="April 2027 (approximate)",
        date_approx_month=4, date_approx_year=2027,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Royal Gorge area.",
    ),

    event(
        slug="beulah-challenge",
        name="Beulah Challenge and OverIt Series",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Beulah, Colorado",
        town="Beulah Valley", county=["Pueblo"], region="southern-colorado",
        ultra_distances=[dist("32 mi", miles=32)],
        companion_distances=[],
        longest_ultra_miles=32, distance_category="50k", fmt="standard",
        date_start="2026-09-19", date_end=None, date_confirmed=True,
        date_display="Sept 19, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Beulah Valley. 32 miles (just above the 50K threshold).",
    ),

    # ── Self-Supported / Special-Format ───────────────────────────────────

    event(
        slug="american-heroes-run",
        name="American Heroes Run",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Longmont, Colorado",
        town="Longmont", county=["Boulder"], region="denver-metro",
        ultra_distances=[dist("100 mi timed", miles=100), dist("24-hr", hours=24)],
        companion_distances=["9-hr timed", "6-hr timed"],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2026-09-11", date_end="2026-09-12", date_confirmed=True,
        date_display="Sept 11–12, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="1.05-mi loop. Timed event; '100 mi' option is a goal distance within the timed format, not a fixed-distance race.",
    ),

    event(
        slug="raising-the-barr",
        name="Raising the Barr",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Brighton, Colorado",
        town="Brighton", county=["Adams"], region="denver-metro",
        ultra_distances=[dist("12-hr", hours=12), dist("6-hr", hours=6)],
        companion_distances=[],
        longest_ultra_miles=None, distance_category="timed", fmt="timed",
        date_start="2026-09-05", date_end=None, date_confirmed=True,
        date_display="Sept 5, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes="Lakeside loop course; solo and relay options.",
    ),

    event(
        slug="gmr-backyard-ultra",
        name="GMR Backyard Ultra",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Golden, Colorado",
        town="Golden", county=["Jefferson"], region="denver-metro",
        ultra_distances=[dist("Backyard (4.2 mi/loop)", loop_miles=4.2)],
        companion_distances=[],
        longest_ultra_miles=None, distance_category="backyard", fmt="backyard",
        date_start="2026-05-23", date_end=None, date_confirmed=True,
        date_display="May 23, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes=None,
    ),

    event(
        slug="last-mountain-man-standing",
        name="Last Mountain Man Standing",
        organizer="Independent",
        organizer_confirmed=False,
        source=["ultraracecalendar.com"],
        coord_key="Conifer, Colorado",
        town="Conifer", county=["Jefferson"], region="denver-metro",
        ultra_distances=[dist("Backyard (4.1 mi/loop)", loop_miles=4.1)],
        companion_distances=[],
        longest_ultra_miles=None, distance_category="backyard", fmt="backyard",
        date_start="2026-07-18", date_end=None, date_confirmed=True,
        date_display="July 18, 2026",
        date_approx_month=None, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="active",
        notes=None,
    ),

    event(
        slug="sourdough-snowshoe-race",
        name="Sourdough Snowshoe Race",
        organizer="Trail Trash Adventures",
        organizer_confirmed=True,
        source=["ultrasignup.com"],
        coord_key="Nederland, Colorado",
        town="Nederland", county=["Boulder"], region="denver-metro",
        ultra_distances=[dist("30K", miles=18.6), dist("18K", miles=11.2)],
        companion_distances=[],
        longest_ultra_miles=18.6, distance_category="sub-50k", fmt="standard",
        date_start=None, date_end=None, date_confirmed=False,
        date_display="Mid-January (typical; 2026 status unverified)",
        date_approx_month=1, date_approx_year=2026,
        year_started=None, year_started_confirmed=False,
        status="unverified",
        notes="Roosevelt National Forest backcountry; ~10,000 ft. Donation-based winter/snowshoe event. Could not be independently confirmed as a currently active event — verify directly with Trail Trash Adventures.",
    ),
]

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print(json.dumps(EVENTS, indent=2, ensure_ascii=False))
